### ISSUE TITLE
`.timeout`

### ISSUE THREAD

**Issue by benjamingr** [jut-io/bluebird-retry#10]
Hey, I'm just wondering why you implemented timing logic given there's `.timeout`

**Comment by aswan** [comment]
Hey Benjamin, I don't really understand your question.  Is the point that if you just want an overall timeout on the retry operation that you can use the bluebird built-in `.timeout()` method?  That's certainly true (at least in theory, I haven't tried it myself), but if you want to do something like "try this operation up to 5 times pausing 1 second between attemps", I'm not seeing how to do that directly with `.timeout()`.  This library can also do backoff (i.e., increase the timeout every time there's a failure), again I don't see how bluebird's `timeout` method would help.
Did I misunderstand your question or overlook something?

**Comment by benjamingr** [comment]
Well, it's just promise chaining, you can do:

    // currentMs determined by whatever logic you want - like backoff
    .timeout(currentMs).catch(Promise.TimeoutError, function(){
         // handle timeout expired
     });

Instead of implementing the logic in the library :)

**Comment by aswan** [comment]
Benjamin, I think we're talking about apples and oranges.  `.timeout()` is useful for a promise that is neither resolved nor rejected for some amount of time.  The timing in retry is about the scenario where a promise is rejected (relatively quickly) and we want to wait for some amount of time, then create a new promise representing another try at the operation.  Those seem like completely different problems to me.  If there is some clever way to cast the latter as the former I'm not seeing it, could you provide a more complete example?
