### ISSUE TITLE
Filter errors

### ISSUE THREAD

**Issue by Janpot** [jut-io/bluebird-retry#12]
Would it be possible to, analog to [bluebird `.catch`](https://github.com/petkaantonov/bluebird/blob/master/API.md#catchfunction-errorclassfunction-predicate-function-handler---promise), make it possible to only retry on certain instances of errors. For instance with `request-promise` I'm only interested in retrying on `RequestError` not on `StatusCodeError`.

Maybe this can be done by accepting a constructor as an option or a predicate-based filter?

**Comment by aswan** [comment]
Hi, that sounds like a great idea (and an even simpler way to handle what was done in #11).  Can you provide a PR?

**Comment by Janpot** [comment]
@aswan I switched to a different library in the meantime, not using `bluebird-retry` anymore.

**Comment by demmer** [comment]
Closing this since there doesn't seem to be any more demand for it. Feel free to reopen and/or submit a PR to add the given functionality.
