### ISSUE TITLE
README typo in an example

### ISSUE THREAD

**Issue by chevin99** [jut-io/bluebird-retry#15]
I was trying some examples on the README, and noticed this line ```throw new Error('bail');}``` needs to have the ```}``` removed at the end in the ```logFail``` example.

```
function logFail() {
    console.log(new Date().toISOString());
    throw new Error('bail');}
}
```

Thanks for your work on this utility, it looks pretty helpful.

**Comment by demmer** [comment]
Whoops, thanks for the catch. Fixed in 5ccf0e7d1eff9c734ad00463f2d5602cc1a6acf1.
