### ISSUE TITLE
Compatibility issues in older browsers and reserved keywords

### ISSUE THREAD

**Issue by arniarent** [jut-io/bluebird-retry#20]
I am using bluebird-retry in a old browser that doesn't seem to support the **Promise.try** in your code, it simply chokes on it because "try" is a reserved keyword.
I do notice bluebird has a fallback option of **Promise.attempt**, and I request that you support this :)

I'm using Opera 11.0 (http://www.opera.com/download/guide/?custom=yes) so you can see how the browser behaves using bluebird-retry.
I can't upgrade the browser because of various reasons.

I've not checked if you're conflicting with other reserved keywords.

**Comment by arniarent** [comment]
Best solution would be to replace all Promise.try with Promise.attempt, and you'll also need to replace Promise.catch with Promise.caught as well. This would make the library compatibility proof with minimum effort. It would not have any adverse effects as both functions are identical.

**Comment by demmer** [comment]
Good suggestion. Fixed.
