### ISSUE TITLE
Feature request: Retry forever

### ISSUE THREAD

**Issue by mwittig** [jut-io/bluebird-retry#4]
Would it be possible to support a "retry forever" mode, e.g. by setting "max_retries: -1". 

Looking at the code this seems to be easy to implement, and it should not pile up the call stack due to the asynchronous execution of the retries.

What do you think?

If you have no time to work on this, I am happy to make a proposal and provide this to via pull request

**Comment by mwittig** [comment]
Ok, I realized that "retry forever" can be done by setting "max_tries: -1". 

Perhaps you could add this as a side note in the README, For example:
If `max_tries` is set to `-1` and no `timeout` is specified, retry will be performed forever.

Apart from this I think you can close the issue. Please let me know if you have concerns about the "retry forever" use.

**Comment by demmer** [comment]
Yes - this is an expected use case. The documentation change you suggested is a good idea -- I'll try to get to it shortly, but if you feel like it, I'd happily take a PR with the changes.
